
import { Participant } from "@/types/participant";

// export const initialParticipants: Participant[] = [];

export const initialParticipants: Participant[] = [
  {
    id: "1",
    name: "Manas Kumar",
    email: "manas@example.com",
    role: "Frontend Engineer",
    isOnline: true,
    micOn: true,
    cameraOn: true,
  },
  {
    id: "2",
    name: "Anuradha Singh",
    email: "anu@example.com",
    role: "Backend Engineer",
    isOnline: false,
    micOn: false,
    cameraOn: false,
  },
  {
    id: "3",
    name: "Rohit Sharma",
    email: "rohit@example.com",
    role: "Product Manager",
    isOnline: true,
    micOn: false,
    cameraOn: true,
  },
  {
    id: "4",
    name: "Priya Verma",
    email: "priya@example.com",
    role: "UI/UX Designer",
    isOnline: true,
    micOn: true,
    cameraOn: false,
  },
  {
    id: "5",
    name: "Amit Patel",
    email: "amit@example.com",
    role: "DevOps Engineer",
    isOnline: false,
    micOn: false,
    cameraOn: false,
  },
  {
    id: "6",
    name: "Sneha Iyer",
    email: "sneha@example.com",
    role: "QA Engineer",
    isOnline: true,
    micOn: true,
    cameraOn: true,
  },
  {
    id: "7",
    name: "Karan Mehta",
    email: "karan@example.com",
    role: "Full Stack Developer",
    isOnline: false,
    micOn: false,
    cameraOn: true,
  },
  {
    id: "8",
    name: "Neha Gupta",
    email: "neha@example.com",
    role: "Business Analyst",
    isOnline: true,
    micOn: true,
    cameraOn: false,
  },
  {
    id: "9",
    name: "Arjun Rao",
    email: "arjun@example.com",
    role: "Engineering Manager",
    isOnline: true,
    micOn: false,
    cameraOn: false,
  },
  {
    id: "10",
    name: "Pooja Nair",
    email: "pooja@example.com",
    role: "Data Engineer",
    isOnline: false,
    micOn: false,
    cameraOn: true,
  },
];
